name: Report a Bug 🪲
description: Create a bug report
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Please provide as much detail as possible so we can evaluate and resolve the bug report quickly.

  - type: markdown
    attributes:
      value: |
        Software-specific details

  - type: input
    id: os
    attributes:
      label: OS and version
      description: Name and version of the operating system used.
      placeholder: OS
    validations:
      required: true

  - type: textarea
    id: bug
    attributes:
      label: Bug
      description: Describe the bug.
      placeholder: Bug description
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Reproduce the Bug
      description: Provide the steps required to reproduce the behavior.
      placeholder: 1. Step 1
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Describe the result you expected.
      placeholder: Result
    validations:
      required: true

  - type: input
    id: hash
    attributes:
      label: Commit hash
      description: Provide the commit hash, if known.
      placeholder: baf2aab0128f07262b564214ec70fc07befc6bb3

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Provide any additional context or screenshots.
