blank_issues_enabled: false
contact_links:
  - name: README
    url: https://github.com/bchainhub/txms.js#readme
    about: Learn more about the project
  - name: Status page
    url: https://txms.info/
    about: View the status of running services
